/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'crassirostris' at '15. 12. 17 오전 12:24' with Gradle 2.8
 *
 * @author crassirostris, @date 15. 12. 17 오전 12:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
